name: "traffic_accidents"
version: "1.0.0"

profile: "duckdb"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  traffic_accidents:
    star:
      +materialized: table
    location_dim:
      +materialized: table # Ensure raw data is stored as a table
    masked_location_dim:
      +materialized: view # Masked version is a view to dynamically apply masking
