import pandas as pd

in_csv = '/tmp/lo_2011_2024.csv'
out_csv = '/tmp/lo_2011_2024_eng.csv'

col_map = {
    "Juhtumi nr": "Case ID",
    "Toimumisaeg": "Time of accident",
    "Isikuid": "Amount of persons",
    "Hukkunuid": "Amount of dead persons",
    "Sõidukeid": "Amount of vehicles",
    "Vigastatuid": "Amount of injured persons",
    "Aadress": "Address",
    "Tänav": "Street",
    "Maja nr": "House number",
    "Ristuv tänav": "Crossing street",
    "Tee nr": "Road number",
    "Tee km": "Road kilometer",
    "Maakond": "County",
    "Omavalitsus": "Commune / Local Government",
    "Asustusüksus": "Village",
    "Asula": "Is the location a settlement",
    "Liiklusõnnetuse liik": "Type of traffic accident (generalized)",
    "Liiklusõnnetuse liik (detailne)": "Type of traffic accident (detailed)",
    "Joobes mootorsõidukijuhi osalusel": "Drunk driver participated",
    "Kergliikurijuhi osalusel": "Light vehicle driver participated",
    "Jalakäija osalusel": "Pedestrian participated",
    "Kaassõitja osalusel": "Passenger participated",
    "Maastikusõiduki juhi osalusel": "Terrain vehicle driver participated",
    "Eaka (65+) mootorsõidukijuhi osalusel": "Elder driver participated",
    "Bussijuhi osalusel": "Bus driver participated",
    "Veoautojuhi osalusel": "Truck driver participated",
    "Ühissõidukijuhi osalusel": "Public transport driver participated",
    "Sõiduautojuhi osalusel": "Car driver participated",
    "Mootorratturi osalusel": "Motorcyclist participated",
    "Mopeedijuhi osalusel": "Moped driver participated",
    "Jalgratturi osalusel": "Cyclist participated",
    "Alaealise osalusel": "Underage participated",
    "Esmase juhiloa omaniku osalusel": "Provisional driving license participated",
    "Turvavarustust mitte kasutanud isiku osalusel": "Safety equipment not used",
    "Mootorsõidukijuhi osalusel": "Motor vehicle driver participated",
    "Tüüpskeemi nr": "Type scheme code",
    "Tüüpskeem": "Type scheme name",
    "Tee tüüp": "Road type (generalized)",
    "Tee tüüp (detailne)": "Road type (detailed)",
    "Tee liik": "Road kind",
    "Tee element": "Road element (generalized)",
    "Tee element (detailne)": "Road element (detailed)",
    "Tee objekt": "Road object",
    "Kurvilisus": "Road curvature",
    "Tee tasasus": "Road hill type",
    "Tee seisund": "Road condition",
    "Teekate": "Road paving",
    "Teekatte seisund": "Road paving condition",
    "Sõiduradade arv": "Number of lanes",
    "Lubatud sõidukiirus": "Allowed driving speed",
    "Ilmastik": "Weather",
    "Valgustus": "Lighting (generalized)",
    "Valgustus (detailne)": "Lighting (detailed)",
    "X koordinaat": "X coordinate",
    "Y koordinaat": "Y coordinate"
}

df = pd.read_csv(in_csv, sep=';')
df = df.rename(columns=col_map)
df.to_csv(out_csv, index=False)
